version: "3.9"
services:
    nginx:
        build: docker/nginx/.
        volumes:
            - ./:/app
        ports:
            - 80:80
    php-fpm:
        build: docker/php-fpm/.
        volumes:
            - ./:/app
    php-cli:
        build: docker/php-cli/.
        volumes:
            - ./:/app
    database:
        image: mysql/mysql-server:8.0
        volumes:
            - ./docker-data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: geolocator
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret2
            MYSQL_USER: forge
